version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: GymFit
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres:/data/postgres
    ports:
      - "5430:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gymFit.org
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "8000:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: